excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://anirudhrata.github.io
title: Forensic ramblings 
tagline: A log of everyday life
description: Some insights into my forensic journey
paginate: 5